# Yerel test istemcisi
client localhost {
    ipaddr = 127.0.0.1
    proto = *
    secret = $ENV{RADIUS_CLIENT_SECRET}
    shortname = localhost
    nas_type = other
}

# OpenVPN, RADIUS açısından NAS istemcisidir.
client openvpn {
    ipaddr = 172.30.0.10
    proto = udp
    secret = $ENV{RADIUS_CLIENT_SECRET}
    shortname = openvpn
    nas_type = other
}

# Red Team brute-force testleri radclient ile buradan gönderilir.
client redteam-toolbox {
    ipaddr = 172.30.0.20
    proto = udp
    secret = $ENV{RADIUS_CLIENT_SECRET}
    shortname = redteam-toolbox
    nas_type = other
}
